### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AndreiLosev** [eva-ics/eva4#1]
Hello. Thanks for a wonderful product. I haven't used it in a production environment yet. However, I would like to know if there are plans to create an SDK in other languages. For example, dart or golang.

**Comment by divi255** [comment]
Thank you for being interested in our product.

EVA ICS is a specialized platform, for our needs we are satisfied with Rust. Sometimes customers ask us to make SDK for other languages (like we have with Python) or community contributors make SDK ports by themselves (like we have with Javascript).

So it really depends on the market situation and interest of the community.

Basically, EVA ICS SDK (EAPI) is built on top of BUS/RT (https://github.com/alttch/busrt). As soon as BUS/RT SDK gets a new language support, EAPI SDK is usually released as well.

**Comment by divi255** [comment]
This week stable release brings services ABI available, so service extensions can be now written in almost any compiling language.

https://info.bma.ai/en/actual/eva4/sdk/abi.html

The release also brings C++ high-level SDK available based on the new ABI.
