### ISSUE TITLE
pubsub output  - not working correctly without reporting interval

### ISSUE THREAD

**Issue by AlexMKX** [eva-ics/eva4#25]
At the moment there are two options: 

1. use interval to send data every X seconds.
2. realtime to send data as they are changed.

Which results in weird behavior for relays and other user-controllable modbus entities.
At startup, mqtt pusher does not send anything because no change is made and respective MQTT entity became unavailable, untill entity state changed (e.g. relay triggered). However, it cannot be changed because it is controlled by user, user cannot control entity because it is unavailable.

Expected behavior: 
1. All entities after startup/autocreation are marked as changed as in fact they are - they created.
2. MQTT detects those entities are changed and pushes data to the broker.

Some side thoughts.
The output missing a throttling behaviour, which means : it should send data at most the interval seconds. E.g. if data changes too often, without interval the broker will be flooded. But if data changex rarely - they should be sent as soon as they changed.

For example:
FAN RPM: changes every 1 seconds, with interval 30 seconds the data will be sent at most every 30 seconds.
Relay state: the confirmation must be sent as soon as it changes. If relay changes it's state, it is weird to wait 30 seconds for getting confirmation from the mobdus (but we must wait because interval is 30 seconds).

Combining above and summing the FRQ:
1. All pubsub entities must be reported at startup or in X seconds after startup.
2. There should be throttling mechanism for spammy sensors, which adopts to entities like relays, which are not spammy and require immediate response to pubsub.

**Comment by divi255** [comment]
Good day,

- all item states are always announced during node startup, after all deployed services had been marked themselves as "ready".  so if there is a unit mapped (I believe you are using pub/sub controller) - its initial state is always pushed into MQTT at the node startup

- a single service restart doesn't announce any initial states as it's a pretty atypical operation in runtime unless the service is deployed/redeployed by a user. in this case use "eva item announce" command to forcibly announce item states to all EAPI subscribers. in case of some automated scenario, announcements can be automated as well, see https://info.bma.ai/en/actual/eva4/core.html#item-announce
